import { motion } from "framer-motion";
import { useState } from "react";
import { Wand2, Send, Sparkles, Bot, User, FileText, Mail } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";

const initial = [
  { role: "ai", text: "Hi! I'm your Recruiter Copilot. Ask me to draft JDs, screen candidates, or schedule interviews." },
  { role: "user", text: "Draft a JD for a Senior ML Engineer." },
  { role: "ai", text: "Here's a draft tailored for a Senior ML Engineer with 5+ yrs in NLP/LLMs and production MLOps experience…" },
];

export default function AIRecruiterCopilotPage() {
  const [msgs, setMsgs] = useState(initial);
  const [input, setInput] = useState("");

  const send = () => {
    if (!input.trim()) return;
    setMsgs([...msgs, { role: "user", text: input }, { role: "ai", text: "Working on it… here's a polished response generated by AI." }]);
    setInput("");
  };

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-6">
      <div>
        <h1 className="page-header">AI Recruiter Copilot</h1>
        <p className="page-subheader">Generate JDs, screen candidates, draft outreach — instantly.</p>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-4">
        <div className="xl:col-span-2 glass-card rounded-xl flex flex-col h-[600px]">
          <div className="p-4 border-b border-border flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg gradient-bg flex items-center justify-center"><Sparkles className="w-4 h-4 text-primary-foreground" /></div>
            <div>
              <p className="font-semibold text-sm">Recruiter Copilot</p>
              <p className="text-xs text-muted-foreground">GPT-powered • Always on</p>
            </div>
          </div>
          <div className="flex-1 overflow-y-auto p-4 space-y-3 scrollbar-thin">
            {msgs.map((m, i) => (
              <div key={i} className={`flex gap-2 ${m.role === "user" ? "justify-end" : ""}`}>
                {m.role === "ai" && <div className="w-7 h-7 rounded-full gradient-bg flex items-center justify-center shrink-0"><Bot className="w-3.5 h-3.5 text-primary-foreground" /></div>}
                <div className={`max-w-[75%] rounded-2xl px-3.5 py-2 text-sm ${m.role === "user" ? "bg-primary text-primary-foreground" : "bg-secondary"}`}>{m.text}</div>
                {m.role === "user" && <div className="w-7 h-7 rounded-full bg-secondary flex items-center justify-center shrink-0"><User className="w-3.5 h-3.5" /></div>}
              </div>
            ))}
          </div>
          <div className="p-3 border-t border-border flex gap-2">
            <Input value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => e.key === "Enter" && send()} placeholder="Ask the copilot…" />
            <Button onClick={send}><Send className="w-4 h-4" /></Button>
          </div>
        </div>

        <div className="space-y-4">
          <Tabs defaultValue="jd">
            <TabsList className="w-full grid grid-cols-3">
              <TabsTrigger value="jd"><Wand2 className="w-3.5 h-3.5 mr-1" />JD</TabsTrigger>
              <TabsTrigger value="email"><Mail className="w-3.5 h-3.5 mr-1" />Email</TabsTrigger>
              <TabsTrigger value="brief"><FileText className="w-3.5 h-3.5 mr-1" />Brief</TabsTrigger>
            </TabsList>
            <TabsContent value="jd" className="space-y-2">
              <Input placeholder="Job title (e.g., Senior PM)" />
              <Input placeholder="Skills (comma separated)" />
              <Textarea placeholder="Notes…" rows={4} />
              <Button className="w-full gap-1"><Sparkles className="w-3.5 h-3.5" /> Generate JD</Button>
            </TabsContent>
            <TabsContent value="email" className="space-y-2">
              <Input placeholder="Candidate name" />
              <Input placeholder="Role" />
              <Button className="w-full gap-1"><Sparkles className="w-3.5 h-3.5" /> Draft Outreach</Button>
            </TabsContent>
            <TabsContent value="brief" className="space-y-2">
              <Textarea placeholder="Paste resume…" rows={6} />
              <Button className="w-full gap-1"><Sparkles className="w-3.5 h-3.5" /> Summarize</Button>
            </TabsContent>
          </Tabs>

          <div className="glass-card rounded-xl p-4">
            <p className="text-xs uppercase tracking-wider text-muted-foreground mb-2">Quick Suggestions</p>
            <div className="flex flex-wrap gap-2">
              {["Screen 12 new resumes", "Schedule 3 interviews", "Send rejection emails", "Compare top 5 candidates"].map((s) => (
                <Badge key={s} variant="secondary" className="cursor-pointer hover:bg-primary/10">{s}</Badge>
              ))}
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
}